import { expect, test, type Page } from '@playwright/test'

async function checkFits(page: Page) {
  await expect.poll(() => page.locator('.preview-page[data-active="true"] .worksheet-sheet').evaluate(element => {
    const paper = element.getBoundingClientRect()
    const canvas = document.querySelector('.preview-canvas')!.getBoundingClientRect()
    return paper.width > 0 && paper.left >= canvas.left && paper.right <= canvas.right + 1 && paper.top >= canvas.top && paper.bottom <= canvas.bottom + 1
  })).toBe(true)
  expect(await page.evaluate(() => ({ x: document.documentElement.scrollWidth > innerWidth, y: document.documentElement.scrollHeight > innerHeight }))).toEqual({ x: false, y: false })
}

test('reference layout keeps both sidebars and whole A4 sheets visible, prints every page at real size', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('complementary', { name: '语文配置' })).toBeVisible()
  const sidebar = page.locator('.workspace-sidebar')
  expect((await sidebar.boundingBox())!.width).toBeGreaterThanOrEqual(260)
  expect(await sidebar.locator('.ant-form-item-label > label').first().evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(12)
  await page.getByRole('radio', { name: '数学', exact: true }).check()
  await expect(page.getByRole('complementary', { name: '数学配置' })).toBeVisible()
  await expect(page.locator('.math-problem')).toHaveCount(92)
  expect(await page.locator('.sidebar-controls').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await checkFits(page)
  await page.screenshot({ path: 'test-results/math-reference.png' })
  await page.getByRole('button', { name: '缩小预览' }).click()
  await checkFits(page)
  await page.getByRole('button', { name: '适应', exact: true }).click()
  await page.getByText('语文', { exact: true }).click()
  await expect(page.getByRole('complementary', { name: '语文配置' })).toBeVisible()
  await expect(page.locator('.preview-summary')).toContainText('共 2 页')
  await expect(page.locator('.preview-page')).toHaveCount(1)
  await checkFits(page)
  await page.screenshot({ path: 'test-results/chinese-reference.png' })
  await page.getByTitle('下一页').click()
  await expect(page.locator('.preview-page[data-active="true"] .chinese-practice-row')).toHaveCount(3)
  for (const viewport of [{ width: 1024, height: 768 }, { width: 1920, height: 1080 }, { width: 800, height: 600 }]) {
    await page.setViewportSize(viewport)
    await checkFits(page)
  }
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.preview-page')).toHaveCount(2)
  await expect(page.locator('.workspace-sidebar')).toBeHidden()
  await expect(page.locator('.preview-tools')).toBeHidden()
  for (const paper of await page.locator('.worksheet-sheet').all()) {
    const dimensions = await paper.evaluate(element => ({ width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height }))
    expect(dimensions.width).toBeCloseTo(210 * 96 / 25.4, 0)
    expect(dimensions.height).toBeCloseTo(297 * 96 / 25.4, 0)
    await expect(paper).toBeVisible()
  }
  await page.pdf({ path: 'test-results/chinese-print.pdf', preferCSSPageSize: true, printBackground: true })
  expect(errors).toEqual([])
})

test('math settings generate the requested format and answers, Chinese blank mode contains no sample glyphs', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('radio', { name: '数学', exact: true }).check()
  await page.getByRole('spinbutton', { name: '题目数量' }).fill('20')
  await expect(page.locator('.math-problem')).toHaveCount(20)
  await expect(page.getByRole('button', { name: '生成作业' })).toHaveCount(0)
  const questions = await page.locator('.math-problem').allTextContents()
  await page.locator('.sidebar-controls .ant-input').first().fill('今日口算')
  await expect(page.locator('.worksheet-header h1')).toHaveText('今日口算')
  await page.getByText('3 列', { exact: true }).click()
  expect(await page.locator('.math-problem').allTextContents()).toEqual(questions)
  await page.getByText('竖式计算', { exact: true }).click()
  await expect(page.locator('.math-vertical')).toHaveCount(20)
  await page.getByText('附答案页', { exact: true }).click()
  await expect(page.locator('.preview-summary')).toContainText('共 2 页')
  await page.getByTitle('下一页').click()
  await expect(page.locator('.math-answer')).toHaveCount(20)
  const answers = page.locator('.preview-page').last().locator('.math-problem')
  for (let index = 0; index < questions.length; index++) {
    const [left, operator, right] = questions[index].split(' ')
    await expect(answers.nth(index).locator('span').first()).toHaveText(questions[index])
    await expect(answers.nth(index).locator('.math-answer')).toHaveText(String(operator === '+' ? Number(left) + Number(right) : Number(left) - Number(right)))
  }
  await page.getByTitle('上一页').click()
  await page.getByText('横式口算', { exact: true }).click()
  expect(await page.locator('.preview-page').first().locator('.math-problem').allTextContents()).toEqual(questions)
  await page.getByRole('spinbutton', { name: '数值范围' }).fill('999999')
  await page.getByRole('spinbutton', { name: '数值范围' }).press('Tab')
  await expect(page.getByRole('spinbutton', { name: '数值范围' })).toHaveValue('100')
  await checkFits(page)
  await page.getByText('语文', { exact: true }).click()
  await page.getByText('空白默写', { exact: true }).click()
  await expect(page.locator('.chinese-practice text')).toHaveCount(0)
  await checkFits(page)
})

test('rule changes are immediate and impossible rules do not leave stale printable questions', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('radio', { name: '数学', exact: true }).check()
  await page.getByRole('spinbutton', { name: '数值范围' }).fill('1')
  await expect(page.locator('.math-problem')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '打印 / 导出 PDF' })).toBeDisabled()
  await expect(page.locator('.preview-canvas')).toContainText('最多生成 6 道不重复题')
  await page.locator('.sidebar-controls .ant-input').first().fill('调整中的作业')
  await page.getByText('20mm', { exact: true }).click()
  await expect(page.locator('.math-problem')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '打印 / 导出 PDF' })).toBeDisabled()
  await page.getByText('避免重复题目', { exact: true }).click()
  await expect(page.locator('.math-problem')).toHaveCount(92)
  for (const text of await page.locator('.math-problem').allTextContents()) {
    expect(text).toMatch(/^[01] [＋+−] [01] =$/)
  }
  await expect(page.getByRole('button', { name: '打印 / 导出 PDF' })).toBeEnabled()
  await checkFits(page)
})

test('copybook content, grid and page settings are reflected immediately', async ({ page }) => {
  await page.goto('/')
  await page.getByText('语文', { exact: true }).click()
  await page.getByRole('textbox', { name: '练习内容' }).fill('山水')
  await expect(page.locator('.chinese-practice-row')).toHaveCount(2)
  await page.getByText('2 行', { exact: true }).click()
  await expect(page.locator('.chinese-practice-row')).toHaveCount(4)
  await page.getByText('方格', { exact: true }).click()
  await expect(page.locator('.chinese-practice path[stroke-dasharray]')).toHaveCount(0)
  await page.getByText('描写', { exact: true }).click()
  await expect(page.locator('.chinese-practice text')).toHaveCount(40)
  await page.getByText('淡粉', { exact: true }).click()
  await expect(page.locator('.chinese-practice text').first()).toHaveAttribute('fill', '#e7a0b8')
  await page.getByText('20mm', { exact: true }).click()
  await expect(page.locator('.worksheet-sheet')).toHaveCSS('padding', '75.5906px')
  await page.getByText('姓名 / 班级 / 日期 / 得分', { exact: true }).click()
  await expect(page.locator('.worksheet-meta')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '换一批题' })).toHaveCount(0)
  await checkFits(page)
})

test('long titles keep student fields and practice content separated on screen and print', async ({ page }) => {
  await page.goto('/')
  for (const subject of ['语文', '数学']) {
    await page.getByRole('radio', { name: subject, exact: true }).check()
    await page.getByText('20mm', { exact: true }).click()
    await page.locator('.sidebar-controls input.ant-input').first().fill('家庭作业'.repeat(10))
    for (const media of ['screen', 'print'] as const) {
      await page.emulateMedia({ media })
      const positions = await page.locator('.worksheet-sheet').first().evaluate(sheet => {
        const header = sheet.querySelector('.worksheet-header')!.getBoundingClientRect()
        const meta = sheet.querySelector('.worksheet-meta')!.getBoundingClientRect()
        const title = sheet.querySelector('h1')!.getBoundingClientRect()
        const content = sheet.querySelector('.chinese-practice, .math-problems')!.getBoundingClientRect()
        return { headerBottom: header.bottom, metaBottom: meta.bottom, titleBottom: title.bottom, metaTop: meta.top, contentTop: content.top }
      })
      expect(positions.titleBottom).toBeLessThanOrEqual(positions.metaTop)
      expect(positions.metaBottom).toBeLessThanOrEqual(positions.headerBottom)
      expect(positions.metaBottom).toBeLessThanOrEqual(positions.contentTop)
    }
    await page.emulateMedia({ media: 'screen' })
  }
})

test('large copybooks mount one page and prepare every row only while printing', async ({ page }) => {
  await page.goto('/')
  await page.getByText('3 行', { exact: true }).click()
  await page.getByText('14', { exact: true }).click()
  await page.getByText('描写', { exact: true }).click()
  await page.getByRole('textbox', { name: '练习内容' }).fill('天'.repeat(1000))
  await expect(page.locator('.preview-page')).toHaveCount(1)
  expect(await page.locator('.chinese-practice-row').count()).toBeLessThan(30)
  expect(await page.locator('*').count()).toBeLessThan(3000)
  await page.getByTitle('下一页').click()
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')))
  await expect(page.locator('.chinese-practice-row')).toHaveCount(3000)
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')))
  await expect(page.locator('.preview-page')).toHaveCount(1)
  expect(await page.locator('.chinese-practice-row').count()).toBeLessThan(30)
  await checkFits(page)
})

test('blank instructions preserve math margins and removing copybook headers reclaims space', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '练习内容' }).fill('天地人你我他春风花草树山')
  await page.getByText('20mm', { exact: true }).click()
  await page.getByText('姓名 / 班级 / 日期 / 得分', { exact: true }).click()
  await expect(page.locator('.preview-summary')).toContainText('共 1 页')
  await expect(page.locator('.chinese-practice-row')).toHaveCount(12)
  await page.getByRole('radio', { name: '数学', exact: true }).check()
  await page.getByRole('spinbutton', { name: '题目数量' }).fill('96')
  await page.locator('.sidebar-controls input.ant-input').nth(1).fill('   ')
  await expect(page.locator('.worksheet-instructions')).toHaveCount(0)
  await page.emulateMedia({ media: 'print' })
  const bottomMargin = await page.locator('.worksheet-sheet').evaluate(sheet => (sheet.getBoundingClientRect().bottom - sheet.querySelector('.math-problems')!.getBoundingClientRect().bottom) * 25.4 / 96)
  expect(bottomMargin).toBeGreaterThanOrEqual(12)
})
